### ISSUE TITLE
AtSearchBar组件的onActionClick不能被触发

### ISSUE THREAD

**Issue by SidneyLann** [NervJS/taro-ui#1042]
### Taro UI 版本信息

3.0.0-alpha.2

### 问题描述

AtSearchBar组件的onActionClick不能被触发，onChange能正常被触发

### 复现步骤

正常使用就能复现

### 复现代码

AtSearchBar value={this.state.keyWord} onChange={this.keyWordChanged} onActionClick={this.searchCommodity} /
![image](https://user-images.githubusercontent.com/5990314/80644355-19c39200-8a9c-11ea-85b4-5c574bd0b9f8.png)

### 报错信息

没报错

### 系统信息

taro 3.0.0-beta.5, taro ui 3.0.0-alpha.2

**Comment by SidneyLann** [comment]
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:2:14)
    at TaroElement.<anonymous> (http://127.0.0.1:64146/appservice/common.js:2012:7)
    at TaroElement.dispatchEvent (http://127.0.0.1:64146/appservice/taro.js:3369:35)
    at Se.eventHandler [as eh] (http://127.0.0.1:64146/appservice/taro.js:1895:14)
    at Object.r.safeCallback (http://127.0.0.1:64146/appservice/__dev__/WAService.js:2:1467232)
    at http://127.0.0.1:64146/appservice/__dev__/WAService.js:2:1586042
    at c (http://127.0.0.1:64146/appservice/__dev__/WAService.js:2:1593979)
    at http://127.0.0.1:64146/appservice/__dev__/WAService.js:2:1585967
    at r (http://127.0.0.1:64146/appservice/__dev__/WAService.js:2:1538494)
    at http://127.0.0.1:64146/appservice/__dev__/WAService.js:2:1538616
