### ISSUE TITLE
jsEnginScriptError Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index");onAppRoute Error: Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index")

### ISSUE THREAD

**Issue by songliwen940523** [NervJS/taro-ui#1050]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by Garfield550** [comment]
麻烦补充一下必要信息

**Comment by luvletterldl** [comment]
又出现了，不明白为什么 taro2.2.14 taro-ui 2.3.4
VM21:1 SystemError (jsEnginScriptError)
Component is not found in path "npm/taro-ui/dist/weapp/components/input/index" (using by "pages/login/login")
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/input/index" (using by "pages/login/login")
    at e (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2152272)
    at e (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2152473)
    at mt (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2172364)
    at Module.Lt (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2179728)
    at Function.value (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2252397)
    at xt (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2268596)
    at http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2273102
    at Mt (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2273623)
    at Function.<anonymous> (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2282563)
    at i.<anonymous> (http://127.0.0.1:38350/appservice/__dev__/WAService.js:2:2244772)

https://github.com/NervJS/taro-ui/issues/1051 里面提到的我也都尝试了，不能解决我的问题。

**Comment by luvletterldl** [comment]
我发现从taro2.2.13升到2.2.14之后少了@tarojs/taro和@tarojs/components这两个依赖
![Uploading image.png…]()

**Comment by vee2046** [comment]
@luvletterldl 解决了吗，我也遇到这个问题了，好奇怪。之前都正常的

**Comment by life1st** [comment]
我也出现了这个bug 检查后发现写了个空的 componentDidMount 去掉之后就好了
