### ISSUE TITLE
编译完成后，在微信开发工具里报错“Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index"”

### ISSUE THREAD

**Issue by songliwen940523** [NervJS/taro-ui#1051]
### Taro UI 版本信息

v2.3.4

### 问题描述

之前编译完都是好好的，都能运行小程序，今天编译完后开发工具里一直报这个错误，我重新安装了taro-ui(cnpm install taro-ui)还是报错，网上查也没查到解决办法
jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index")
    at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)
    at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1567078)
    at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1588948
    at Module.He (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1589527)
    at Function.value (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1679884)
    at Et (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036)
    at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700298
    at Dt (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700791)
    at Function.<anonymous> (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1704378)
    at i.<anonymous> (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1672721)

### 复现步骤

npm run dev:weapp编译成功后开发工具里报错

### 复现代码

import { AtInput, AtList, AtListItem, AtActivityIndicator, AtButton ,AtAvatar} from 'taro-ui'

### 报错信息

jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index")
    at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)
    at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1567078)
    at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1588948
    at Module.He (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1589527)
    at Function.value (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1679884)
    at Et (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036)
    at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700298
    at Dt (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700791)
    at Function.<anonymous> (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1704378)
    at i.<anonymous> (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1672721)

### 系统信息

taro v2.2

**Comment by songliwen940523** [comment]
目前发现dist\npm\taro-ui\dist\weapp\components\list目录下缺少index.wxml，是不是缺少这个文件导致的，请问编译完为什么会缺少这个文件？

**Comment by songliwen940523** [comment]
为什么我编译完后dist\npm目录下两个文件_taro-ui@2.3.4@taro-ui和taro-ui，文件_taro-ui@2.3.4@taro-ui中存放了wxml文件，文件taro-ui中存放了js和json文件

**Comment by songliwen940523** [comment]
我把两个文件手动合并到了taro-ui中，问题就解决了，请问一下为什么编译会出这样的问题，编译出两个taro-ui文件

**Comment by Garfield550** [comment]
试一下 Taro v2.2.3 可以吗，不行就退回 Taro v2.1.6 试一下。

**Comment by wulianglaoge** [comment]
> 我把两个文件手动合并到了taro-ui中，问题就解决了，请问一下为什么编译会出这样的问题，编译出两个taro-ui文件

我合并之后不报错了，但是页面还是空的

**Comment by songliwen940523** [comment]
> 试一下 Taro v2.2.3 可以吗，不行就退回 Taro v2.1.6 试一下。

回退taro v 2.1.6问题解决。

另外再多问一个问题，我编译完后一直会提示缺少sitemap.json文件，这个该如何解决？（我每次都是手动复制一个进去）
sitemap.json
Error: 未找到入口 sitemap.json 文件，或者文件读取失败，请检查后重新编译。

**Comment by Garfield550** [comment]
`sitemap.json` 的问题也是 Taro 的问题，所以还是需要去 Taro 那边提一下的。

**Comment by Garfield550** [comment]
#1050 应该是和这个问题一样的，所以那个问题就先关掉了。

**Comment by haoyinag** [comment]
@Garfield550 @songliwen940523

**Comment by haoyinag** [comment]
1. 根目录新增`sitemap.json`文件；
2. 文件添加配置(参考)
   ```json
   {
     "rules": [
       {
         "action": "allow",
         "page": "path/to/page",
         "params": ["a", "b"],
         "matching": "exact"
       },
       {
         "action": "disallow",
         "page": "path/to/page"
       }
     ]
   }
   ```
3. `config/index.js`文件的`config`内添加`sitemapLocation: 'sitemap.json',`
4. 重新编译
5. 如果还是提示问题，把开发者工具重启，清除缓存；如果还是不行，删除`node_modules`，重新`yarn`。

**Comment by ublooth** [comment]
> 1. 根目录添加`sitemap.json`文件；
> 2. 文件添加配置（参考）
>    ```json
>    {
>       “规则”：[
>        {
>          “操作”： “允许”，
>           “页面”： “路径/到/页面”，
>           “参数”：[ “ a ”， “ b ” ]，
>           “匹配”： “精确”
>        }，
>        {
>          “操作”： “禁止”，
>           “页面”： “路径/到/页面”
>        }
>      ]
>    }
>    ```
> 3. `config/index.js`文件的`config`内添加`sitemapLocation: 'sitemap.json',`
> 4. 重新编译
> 5. 如果还是提示问题，把开发者工具重新启动，清除缓存；如果还是不行，删除`node_modules`，重新`yarn`。



> ### 芋头UI版本信息
> v2.3.4
> 
> ### 问题描述
> 之前编译完都是好好的，可以运行小程序，今天编译完后开发工具里一直报这个错误，我重新安装了taro-ui（cnpm install taro-ui）还是报错，网上查也没查到解决办法
> jsEnginScriptError
> 在路径“ npm / taro-ui / dist / weapp / components / list / item / index”中找不到组件（通过“ pages / index / index”使用）； onAppRoute
> 错误：在路径“ npm中找不到组件/ taro-ui / dist / weapp / components / list / item / index”（由“ pages / index / index”使用）
> 在q（[http://127.0.0.1:50882/appservice/__dev__/WAService.js:2 ：1566874](http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)），
> 位于q（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1567078），
> 位于http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1588948
> 在Module.He（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1589527）
> 在 Et（[http://127.0.0.1:50882/appservice/__dev__/WAService.js:2：](http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036)在Function.value（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1679884）
> 处[： 1696036](http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036)）
> 在http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700298
> 在申（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700791）
> 在功能。（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1704378）
> 在i。（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1672721）
> 
> ### 复现步骤
> npm run dev：weapp编译成功后开发工具里报错
> 
> ### 复现代码
> 从“ taro-ui”导入{AtInput，AtList，AtListItem，AtActivityIndi​​cator，AtButton，AtAvatar}
> 
> ### 报错信息
> jsEnginScriptError
> 组件在路径“ npm / taro-ui / dist / weapp / components / list / item / index”中找不到（通过“页面/索引/索引”使用）； onAppRoute
> 错误：在路径“ npm /中找不到组件
> 位于q（[http://127.0.0.1:50882/appservice/__dev__/WAService.js:2的](http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)taro-ui / dist / weapp / components / list / item / index“（由“ pages / index / index”使用）[： 1566874](http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)）
> 在q（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1567078）
> 在http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1588948
> 在Module.He（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1589527）
> 位于Function.value（[http://127.0.0.1:50882/appservice/__dev__/WAService.js:2 ：1679884](http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1679884)）
> 在逸（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036）
> 在http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700298
> 在申（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700791）
> 。（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1704378）
> 在i。（http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1672721）
> 
> ### 系统信息
> 芋头v2.2
> 
> ### 补充信息

你好。请问你的问题解决了吗？我也遇到这个问题，但是我的情况是在本地npm run dev:weapp运行没有问题，build打包后才会出现这个问题

**Comment by ublooth** [comment]
> ### Taro UI 版本信息
> v2.3.4
> 
> ### 问题描述
> 之前编译完都是好好的，都能运行小程序，今天编译完后开发工具里一直报这个错误，我重新安装了taro-ui(cnpm install taro-ui)还是报错，网上查也没查到解决办法
> jsEnginScriptError
> Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index");onAppRoute
> Error: Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index")
> at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)
> at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1567078)
> at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1588948
> at Module.He (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1589527)
> at Function.value (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1679884)
> at Et (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036)
> at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700298
> at Dt (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700791)
> at Function. (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1704378)
> at i. (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1672721)
> 
> ### 复现步骤
> npm run dev:weapp编译成功后开发工具里报错
> 
> ### 复现代码
> import { AtInput, AtList, AtListItem, AtActivityIndicator, AtButton ,AtAvatar} from 'taro-ui'
> 
> ### 报错信息
> jsEnginScriptError
> Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index");onAppRoute
> Error: Component is not found in path "npm/taro-ui/dist/weapp/components/list/item/index" (using by "pages/index/index")
> at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1566874)
> at q (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1567078)
> at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1588948
> at Module.He (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1589527)
> at Function.value (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1679884)
> at Et (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1696036)
> at http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700298
> at Dt (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1700791)
> at Function. (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1704378)
> at i. (http://127.0.0.1:50882/appservice/__dev__/WAService.js:2:1672721)
> 
> ### 系统信息
> taro v2.2
> 
> ### 补充信息

你好。请问这个问题解决了吗？我的情况是在npm run dev:weapp运行正常，npm run build:weapp打包后就出现这个问题

**Comment by ublooth** [comment]
> 1. 根目录新增`sitemap.json`文件；
> 2. 文件添加配置(参考)
>    ```json
>    {
>      "rules": [
>        {
>          "action": "allow",
>          "page": "path/to/page",
>          "params": ["a", "b"],
>          "matching": "exact"
>        },
>        {
>          "action": "disallow",
>          "page": "path/to/page"
>        }
>      ]
>    }
>    ```
> 3. `config/index.js`文件的`config`内添加`sitemapLocation: 'sitemap.json',`
> 4. 重新编译
> 5. 如果还是提示问题，把开发者工具重启，清除缓存；如果还是不行，删除`node_modules`，重新`yarn`。
我的情况是在npm run dev:weapp运行正常，npm run build:weapp打包后就出现这个问题，按照你的步骤还是一样的问题

**Comment by PhantomRay** [comment]
这个和 #1210 应该是一个问题。
我挨个测试了一下，2.1.6不会出现这个问题。之后都会有同样问题。

taro 2.2.15 `npm run build:weapp`会出这个错，`npm run dev:weapp`不会出错

应该和这个有关：https://github.com/NervJS/taro/issues/7694

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/issues/7913#issuecomment-723991922
请尝试下

**Comment by PhantomRay** [comment]
> [NervJS/taro#7913 (comment)](https://github.com/NervJS/taro/issues/7913#issuecomment-723991922)
> 请尝试下

有效

**Comment by xiyionxiong** [comment]
重启微信开发者工具后解决
