### ISSUE TITLE
taro3.0.0中使用taro-ui报错

### ISSUE THREAD

**Issue by darkfiredarkhalo** [NervJS/taro-ui#1112]
**问题描述**
- 基于`taro3.0.0`创建项目(typescript/react模板/普通css),安装`taro-ui`:`yarn add taro-ui`,版本是`2.3.4`;  
- 在`app.ts`中引入全局样式`import 'taro-ui/dist/style/index.scss`;  
- 在page中使用`import { AtButton } from 'taro-ui`;  
- 运行项目`yarn dev:weapp`  
报错信息如下:  
```
./node_modules/taro-ui/dist/weapp/index.ts
Module not found: Can't resolve './style/index.scss' in '/xxx/..../node_modules/taro-ui/dist/weapp'  
```  
见如上报错之后修改`node_modules/taro-ui/dist/weapp/index.ts`中的样式导入路径为  
```
import '../style/index.scss'
import '../style/themes/red.scss'
import '../style/themes/purple.scss'  
```  
编译正常,使用小程序开发工具打开小程序,报错信息如下:  
```
MiniProgramError
Super expression must either be null or a function
TypeError: Super expression must either be null or a function
    at _inherits (http://127.0.0.1:61988/appservice/vendors.js:288:11)
    at http://127.0.0.1:61988/appservice/pages/index/index.js:2831:146
    at Object../node_modules/taro-ui/dist/weapp/common/component.tsx (http://127.0.0.1:61988/appservice/pages/index/index.js:2860:2)
    at __webpack_require__ (http://127.0.0.1:61988/appservice/runtime.js:81:30)
    at Object../node_modules/taro-ui/dist/weapp/components/action-sheet/index.tsx (http://127.0.0.1:61988/appservice/pages/index/index.js:3606:75)
    at __webpack_require__ (http://127.0.0.1:61988/appservice/runtime.js:81:30)
    at Module../node_modules/taro-ui/dist/weapp/index.ts (http://127.0.0.1:61988/appservice/pages/index/index.js:13151:82)
    at __webpack_require__ (http://127.0.0.1:61988/appservice/runtime.js:81:30)
    at Object../node_modules/taro-ui/dist/index.js (http://127.0.0.1:61988/appservice/pages/index/index.js:2761:20)
    at __webpack_require__ (http://127.0.0.1:61988/appservice/runtime.js:81:30)  
```

**复现步骤**
- 基于`taro3.0.0`创建项目(typescript/react模板/普通css),安装`taro-ui`:`yarn add taro-ui`,版本是`2.3.4`;  
- 在`app.ts`中引入全局样式`import 'taro-ui/dist/style/index.scss`;  
- 在page中使用`import { AtButton } from 'taro-ui`;  
- 运行项目`yarn dev:weapp`    

**期望行为**
在`taro3.0.0`中正常使用`taro-ui`

**报错信息**
见问题描述

**系统信息**
```
Taro CLI 3.0.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.0 => 3.0.0 
      @tarojs/components: 3.0.0 => 3.0.0 
      @tarojs/mini-runner: 3.0.0 => 3.0.0 
      @tarojs/react: 3.0.0 => 3.0.0 
      @tarojs/runtime: 3.0.0 => 3.0.0 
      @tarojs/taro: 3.0.0 => 3.0.0 
      @tarojs/webpack-runner: 3.0.0 => 3.0.0 
      babel-preset-taro: 3.0.0 => 3.0.0 
      eslint-config-taro: 3.0.0 => 3.0.0 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^2.3.4 => 2.3.4 
```

**Comment by darkfiredarkhalo** [comment]
补充问下:  Taro-UI支持HOOKS吗?

**Comment by darkfiredarkhalo** [comment]
更换taro-ui版本到3.0.0-alpha.1之后正常了, `yarn add taro-ui@3.0.0-alpha.1`
