### ISSUE TITLE
按钮对象在提交表单时报错

### ISSUE THREAD

**Issue by keyss2014** [NervJS/taro-ui#1169]
**问题描述**

**复现步骤**
创建一个仅包含一个输入框的Form表单
const Login: React.FC<{}> = (props) => {
    const [state, setstate] = useState('tempdata');
    const onChange = (v) => {
        setstate(v);
    }
    const submitForm = (event: CommonEvent) => {
        console.log(state)
    }

    const resetForm = () => {
    }
    return <AtForm onSubmit={submitForm} onReset={resetForm}>
        <AtInput name='name' onChange={onChange} value={state}></AtInput>
        <AtButton formType='submit'>提交</AtButton>
        <AtButton formType='reset'>重置</AtButton>
    </AtForm>
}
export default Login;
可以正常编译，但是在打开小程序点击按钮时无响应，查看控制台有报错，具体信息见下。
以上例子如果换为标准的button按钮一切正常。

**期望行为**
可以正常打印表单信息

**报错信息**

Cannot read property 'triggerEvent' of undefined; [Component] Event Handler Error @ pages/login/index#bound eventHandler
TypeError: Cannot read property 'triggerEvent' of undefined
    at AtButton.onReset (http://127.0.0.1:39160/appservice/vendors.js:5135:27)
    at TaroElement.dispatchEvent (http://127.0.0.1:39160/appservice/taro.js:4648:35)
    at H.eventHandler [as eh] (http://127.0.0.1:39160/appservice/taro.js:3029:16)

**系统信息**

**补充信息**
看了源码后，感觉以下代码存在bug
https://github.com/NervJS/taro-ui/blob/dev/src/components/button/index.tsx
在运行时$scope为未定义
private onSumit(event: CommonEvent): void {
    if (this.state.isWEAPP || this.state.isWEB) {
      this.$scope.triggerEvent('submit', event.detail, {
        bubbles: true,
        composed: true
      })
    }
  }

  private onReset(event: CommonEvent): void {
    if (this.state.isWEAPP || this.state.isWEB) {
      this.$scope.triggerEvent('reset', event.detail, {
        bubbles: true,
        composed: true
      })
    }
  }

**Comment by LbhFront-end** [comment]
一样的问题

**Comment by easycat** [comment]
一样的问题

**Comment by eruca** [comment]
一样的问题

**Comment by plaknight** [comment]
一样的问题

**Comment by JX-Zhuang** [comment]
我也遇到这个问题了

**Comment by mulianju** [comment]
同样遇到这个问题了，咋还没解决

**Comment by JuSanZhi** [comment]
我也遇到同样的问题，编译成小程序就会报这个错
![image](https://user-images.githubusercontent.com/24559368/116356931-7cc24300-a82e-11eb-82f9-017a599839cb.png)
