### ISSUE TITLE
同样遇到该问题，版本："taro-ui": "^3.0.0-alpha.3"

### ISSUE THREAD

**Issue by Wu981214** [NervJS/taro-ui#1530]
同样遇到该问题，版本："taro-ui": "^3.0.0-alpha.3"

VM2523 WAService.js:2 (in promise) MiniProgramError
Cannot read property 'width' of null
TypeError: Cannot read property 'width' of null
    at Object.n.handleDomInfo [as onQueryedDom] (http://127.0.0.1:52824/appservice/vendors.js:2:165400)
    at http://127.0.0.1:52824/appservice/vendors.js:2:163752

_Originally posted by @synebula in https://github.com/NervJS/taro-ui/issues/727#issuecomment-727690193_

**Comment by wanglihuaya** [comment]
我也有这个问题 老哥解决了吗
