### ISSUE TITLE
官方交流群

### ISSUE THREAD

**Issue by jimczj** [NervJS/taro-ui#16]
## Taro UI 官方交流群

![image](https://user-images.githubusercontent.com/13499146/44708641-3eeb4a80-aada-11e8-94c3-d3b425cb474e.png)

![image](https://user-images.githubusercontent.com/13499146/44708803-a608ff00-aada-11e8-8b95-e4b2eed64655.png)

**Comment by HongDanMan** [comment]
二维码失效了

**Comment by dsitn201703** [comment]
为什么添加了小助手好友之后，发送Taro UI并没有拉我入群呢？

**Comment by wang89jun** [comment]
二维码过期，我用了less ,如何在taro中引入taro-ui的样式

**Comment by arronlovepudding** [comment]
为什么taro-ui在部分安卓手机的企业微信中样式会失效？
测试环境：华为麦芒RNE-AL00 企业微信版本号 2.7.2

**Comment by heroSoft205** [comment]
**安装taro-ui出错**
1、先初始化项目 taro init myApp
2、安装组件  npm install taro-ui
然后出现错误
E:\taro\myApp>npm install taro-ui
npm WARN tar ENOENT: no such file or directory, open 'E:\taro\myApp\node_modules\.staging\fsevents-8aaccbb2\node_modules\minimist\.travis.yml'
npm WARN @webpack-contrib/schema-utils@1.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\_chokidar@2.1.2@chokidar\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\taro\myApp\node_modules\.staging\fsevents-8aaccbb2\node_modules\aproba' -> 'E:\taro\myApp\node_modules\.staging\aproba-0d300e72'

npm ERR! path E:\taro\myApp\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'E:\taro\myApp\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name' -> 'E:\taro\myApp\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mi\AppData\Roaming\npm-cache\_logs\2019-03-02T01_18_16_179Z-debug.log
这是怎么回事？有人遇到过没？求帮忙！感谢

**Comment by koppthe** [comment]
@heroSoft205 换 cnpm 试一下吧

**Comment by WangxinsHub** [comment]
引入taro ui就编译失败


错误  编译失败  node_modules/@tarojs/taro-weapp/dist/index.js
{ TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "ObjectExpression"
    at validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18) _babel: true }

**Comment by jimczj** [comment]
@wang89jun 请单独发issue，该 issue 不讨论问题

**Comment by AllenJacen** [comment]
> 二维码过期，我用了less ,如何在taro中引入taro-ui的样式
我也是一样的问题，请问你解决了吗？less如何覆盖原来的样式

**Comment by koppthe** [comment]
@AllenJacen  你可以开个新的 issue 问的，要覆盖 SCSS 变量，得用 SCSS 来写呀

**Comment by Chad97** [comment]
> ## Taro UI 官方交流群
> ![image](https://user-images.githubusercontent.com/13499146/44708803-a608ff00-aada-11e8-8b95-e4b2eed64655.png)

小助手挂掉了，调加好友迟迟没回复

**Comment by hbsjmsjwj** [comment]
我的Taro项目用Less怎么引入Taro ui的样式

**Comment by cham1985** [comment]
这 项目 烂尾了？  没人加群 ？

**Comment by koppthe** [comment]
@cham1985 你可以看看 taro 的 commit log，怎么会烂尾呢。加群的小助手最近比较忙，所以加群请求没能及时处理

**Comment by cham1985** [comment]
@koppthe  再忙 利用 拉屎时间也能加好多人 进群啊？ 15921952796，求 入群

**Comment by SzHeJason** [comment]
已拉

**Comment by BinZhiZhu** [comment]
求拉群哟 ZZB19960816 @SzHeJason @koppthe

**Comment by Here21** [comment]
求拉 @SzHeJason

**Comment by leechaouser** [comment]
> 求拉群哟 ZZB19960816 @SzHeJason @koppthe

求拉

**Comment by ljl793647411** [comment]
taro-ui样式为什么在百度小程序上不生效~

**Comment by Linyccc** [comment]
taro-ui 引进去就报错。

**Comment by forconz** [comment]
加我微信481933，我创建群活码

**Comment by userL0901** [comment]
taro一直下载不成功，项目无法启动，taro不是内部命令

**Comment by FredLee1995** [comment]
为什么Atextarea   的change时间 不触发

**Comment by ixiaofeiyang** [comment]
求拉群，微信：15692121959

**Comment by Json-Luo** [comment]
微信号：Nishino-Luo    求拉群~

**Comment by shatian114** [comment]
微信：m1320024819，求拉群

**Comment by RickChenCX** [comment]
微信：15921173035，求拉群。另外，问一下，后面会支持taro next吗？

**Comment by yz1311** [comment]
> 微信：15921173035，求拉群。另外，问一下，后面会支持taro next吗？

"taro-ui": "3.0.0-alpha.2"

**Comment by liufa520** [comment]
你好，二维码失效了

**Comment by JserShadow** [comment]
微信：a13059015637，求拉群

**Comment by anTi-by** [comment]
taro3.0 vue 版 不能使用taro-ui 吗，求拉群 tianflowerfeng

**Comment by xinchen37** [comment]
组件没有做国际化吗？

**Comment by citrusjunoss** [comment]
有没有计划做独立H5版本，antd-mobile 太难用了

**Comment by zula1994** [comment]
二维码图片失效了，请问怎么进群吖？

**Comment by duxinyues** [comment]
根据官方的文档，taro-ui根本就不能引用
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss]
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss.js]
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss.jsx]
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss.ts]
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss.tsx]
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss.mjs]
[/home/yd/code/taro/taro_21/node_modules/taro-ui/dist/weapp/style/themes/red.scss.vue]
 @ ./node_modules/taro-ui/dist/weapp/index.ts 3:0-33
 @ ./node_modules/taro-ui/dist/index.js
 @ ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib!./src/pages/index/index.tsx
 @ ./src/pages/index/index.tsx

**Comment by cangcudelunzhuan** [comment]
317051801 求入群

**Comment by asd75944** [comment]
qq395897187 求入群，有很多问题

**Comment by nuoer2048** [comment]
微信： a1947331378 求拉群， 感谢

**Comment by suzhimin1** [comment]
taro ui组件样式按需引用为啥一直报错不生效。

**Comment by kunkuntang** [comment]
qq 734229080 求拉群， taro ui 引入样式后报错，安装 alpha 才可以

**Comment by oMhuAaN** [comment]
taro-ui无法安装，终端提示如下：
yarn add taro-ui
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
⠠ regenerator-runtime@^0.13.4

**Comment by zzzhan** [comment]
Picker 的mode=region是 不 是在H5 不支持。 区域信息不显示。（没人位进群只能在这问）

**Comment by zzzhan** [comment]
什么时候更新版本。怎么合并了PR后没发版呢？ @luckyadam

**Comment by Rengge** [comment]
微信：13058382275 ，求拉群

**Comment by honlyHuang** [comment]
> 微信：13058382275 ，求拉群

扫码，发送关键词不能入群吗？

**Comment by WEBTMM** [comment]
微信：TMOCT5  求拉群   使用taro搭建项目 引入taroUI引入页面报错，提示：node_modules/taro-ui/dist/h5/components/accordion/index.js: Support for the experimental syntax 'jsx' isn't currently enabled

**Comment by ctocto** [comment]
不维护了吗❓

**Comment by HappyYA** [comment]
不维护了也不发个声明？大公司就这点责任心？

**Comment by youngluo** [comment]
最新代码怎么没有合并主分支呢

**Comment by tanwei0425** [comment]
> 

https://github.com/tanwei0425/taro-3.x-redux-hooks-template

**Comment by tinfoil67** [comment]
求好心人拉群 微信：xglkl67

**Comment by Yongest** [comment]
> 二维码失效了

官方微信没有回复，加微信：lovemy2022 ,回复taro，入taro群。

**Comment by yangdong0000** [comment]
at setup (C: Users yangdong01 Desktop taroscss yy node modules atarojs iebpack5-prebundle src prebundle bundle.ts:116:13)at handlePlugins (C: Usersyangdong01 Desktop taroscssyy node modules esbuild lib main.js:855:23)at Object.buildorServe (C: Users yangdong01 Desktop taroscss yy node modules esbuild lib main.js:1149:7)at C: Users yangdong01 Desktop taroscss yy nodeles esbuild lib main.is:2119:17at new Promise (<anonymous>at Object.build (C: Usersyangdong01 Desktop taroscss yy node moduleslesbuild lib main,is:2109:14at Object.build (C:\Usersyangdong01\Desktop\taroscss yy node moduleslesbuild lib main.js:1956:51at C: \Users yangdong01\Desktop taroscss yy node modules @tarojs livebpack5-prebundle src prebundle bundle.ts:70: 18at Generator.next (<anonymous>)
The plugin "entry" was triggered by this importnode modules/taro-ui/dist/weapp/index.ts:2:7:'./style/index.scssimport
i dist weapp'
(ERROR [plugin entry] Can't resolve "./style/themes/red.scss’in 'C: Users yangdong01\Desktop)taroscss yy node modules taro-ui
引入taro-ui的样式循环报错

**Comment by free-booter** [comment]
求拉群 China_lllllllll

**Comment by b-yp** [comment]
Taro-UI 不维护了吗？
我这边有个功能想加到组件上，我可以自己提 PR，但是怕项目无人维护，PR 不会有人合并

**Comment by bxter** [comment]
这么好的项目，感觉每人维护了

**Comment by weysl33-boop** [comment]
暂停了吗

**Comment by pyy-alt** [comment]
不维护了？

**Comment by robinv8** [comment]
最近重启维护了

**Comment by pyy-alt** [comment]
> 最近重启维护了

我换成了 nutui-react 😊
