### ISSUE TITLE
AtSwipeAction 加载时候报错TypeError: Cannot read properties of null (reading 'width')

### ISSUE THREAD

**Issue by Zhao187** [NervJS/taro-ui#1786]
**问题描述**
taro3使用taro ui中的AtSwipeAction做滑动删除，界面加载中报错TypeError: Cannot read properties of null (reading 'width')

**复现步骤**
```js
1.import {AtButton, AtList, AtListItem, AtNavBar,AtSwipeAction} from 'taro-ui'

<AtList hasBorder={true}>
          {
            this.state.list.map((item, index) => {
              return (
                <AtSwipeAction key={index} onClick={(data, index, event)=>{
   
                }} options={[
                  {
                    text: '删除',
                    style: {
                      backgroundColor: '#FF4949'
                    }
                  }
                ]}>
                  <AtListItem
                    key={index}
                    title={item.friendNickname}
                    thumb={item.friendFaceImage}
                    note={item.msg}
                    extraText={item.isRead ? '' : '未读'}
                  />
                </AtSwipeAction>
                )
            })
          }
        </AtList>
```

**期望行为**
控制台不报错，可以正常使用

**报错信息**
index.esm.js:6128 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'width')
    at AtSwipeAction.eval (index.esm.js:6128:50)
    at step (index.esm.js:218:17)
    at Object.eval [as next] (index.esm.js:167:14)
    at fulfilled (index.esm.js:126:24)

**系统信息**
- Taro 版本 v3.6.27
 - Taro UI 版本  v3.3.0
 - 报错平台  h5, weapp

**补充信息**
无

**Comment by SiNanQrn** [comment]
我也遇到这个问题了

**Comment by SiNanQrn** [comment]
我也遇到这个问题了

**Comment by Cathy-Majie** [comment]
我也遇到了这个问题

**Comment by superchenwb** [comment]
我也遇到了

**Comment by xieyanxx** [comment]
我也遇到了这个问题请问是怎么解决的呢
