### ISSUE TITLE
taro-ui打包小程序出现value无效问题

### ISSUE THREAD

**Issue by zhengxingrong** [NervJS/taro-ui#185]
Cannot read property 'value' of null; [Component] Lifetime Method Error @ npm/taro-ui/dist/weapp/components/icon/index#attached
TypeError: Cannot read property 'value' of null
    at filterProps (http://127.0.0.1:45407/appservice/npm/@tarojs/taro-weapp/dist/index.js:3130:71)
    at V.initComponent (http://127.0.0.1:45407/appservice/npm/@tarojs/taro-weapp/dist/index.js:3235:21)
    at V.attached (http://127.0.0.1:45407/appservice/npm/@tarojs/taro-weapp/dist/index.js:3300:23)
    at r.safeCallback (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:463038)
    at r.call (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:462935)
    at r (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:477387)
    at r (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:477700)
    at r (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:477642)
    at S (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:477710)
    at Function.w.pretendAttached (http://127.0.0.1:45407/appservice/__dev__/WAService.js:1:487629)

**Comment by jimczj** [comment]
taro 跟 taro-ui 的版本是多少

**Comment by zhengxingrong** [comment]
可以了，谢谢了哈

**Comment by zhengxingrong** [comment]
已解决

**Comment by zhengxingrong** [comment]
已解决
