### ISSUE TITLE
AtImagePicker 报错

### ISSUE THREAD

**Issue by zhoushenghua** [NervJS/taro-ui#211]
### 重现步骤
import { AtImagePicker } from 'taro-ui'
### 依赖的版本号

node: v10.13.0  Taro:1.2.0-beta.4  Taro-UI: 1.5.0
### 实际结果
thirdScriptError
index is not defined; [Component] Property Observer Error @ npm/taro-ui/dist/weapp/components/image-picker/index#observer
ReferenceError: index is not defined
    at AtImagePicker._createData (http://127.0.0.1:55436/appservice/npm/taro-ui/dist/weapp/components/image-picker/index.js:214:16)
    at doUpdate (http://127.0.0.1:55436/appservice/npm/@tarojs/taro-weapp/dist/index.js:3563:22)
    at updateComponent (http://127.0.0.1:55436/appservice/npm/@tarojs/taro-weapp/dist/index.js:3548:5)
    at V.observer (http://127.0.0.1:55436/appservice/npm/@tarojs/taro-weapp/dist/index.js:3076:7)
    at Function.r.safeCallback (http://127.0.0.1:55436/appservice/__dev__/WAService.js:1:463149)
    at n.<anonymous> (http://127.0.0.1:55436/appservice/__dev__/WAService.js:1:495357)
    at b (http://127.0.0.1:55436/appservice/__dev__/WAService.js:1:472854)
    at o.doUpdates (http://127.0.0.1:55436/appservice/__dev__/WAService.js:1:474066)
    at t.applyProperties (http://127.0.0.1:55436/appservice/__dev__/WAService.js:1:558851)
    at Function.value (http://127.0.0.1:55436/appservice/__dev__/WAService.js:1:574708)

**Comment by darkmice** [comment]
我也碰到这个错误了

**Comment by jimczj** [comment]
Taro 1.2.0-beta.4 版本有问题，使用1.2.0-beta.3 或1.2.0-beta.2，cli 也是
