### ISSUE TITLE
AtTabBar reports webviewScriptError in wechat develop tool

### ISSUE THREAD

**Issue by zhoucs624** [NervJS/taro-ui#237]
### 重现步骤
按照<a href="https://taro-ui.aotu.io/#/docs/tabbar" target="_blank">示例</a>编写，在开发模式下，在微信开发者工具运行时，点击一个tab报错
### 依赖的版本号

- node: v8.11.3
- taro: v1.1.9
- taro-ui: v1.5.1

### 预期结果
正常切换没有异常

### 实际结果

webviewScriptError
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
    at v (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:20:3894)
    at r.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:20:5014)
    at o.safeCallback (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:5:11511)
    at o.call (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:5:11275)
    at n (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:5:13741)
    at http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:5:14295
    at s (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:5:13309)
    at Function.o.dispatchEvent (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:5:14196)
    at t (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:7:9572)
    at g (http://127.0.0.1:23876/__pageframe__/__dev__/WAWebview.js:7:10057)
(anonymous) @ VM2254:2

**Comment by jimczj** [comment]
更新微信小程序基础调试库至 2.3.2 即可解决
