### ISSUE TITLE
Cannot read property 'designWidth' of undefined

### ISSUE THREAD

**Issue by nevernet** [NervJS/taro-ui#350]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

```
Cannot read property 'designWidth' of undefined; [Component] Property Observer Error @ npm/taro-ui/dist/weapp/components/icon/index#observer
TypeError: Cannot read property 'designWidth' of undefined
    at Object.pxTransform (http://127.0.0.1:33360/appservice/npm/@tarojs/taro-weapp/dist/index.js:4210:33)
    at AtIcon._createData (http://127.0.0.1:33360/appservice/npm/taro-ui/dist/weapp/components/icon/index.js:81:40)
    at doUpdate (http://127.0.0.1:33360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3659:22)
    at updateComponent (http://127.0.0.1:33360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3644:5)
    at V.observer (http://127.0.0.1:33360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3162:7)
    at Function.r.safeCallback (http://127.0.0.1:33360/appservice/__dev__/WAService.js:1:545426)
    at n.<anonymous> (http://127.0.0.1:33360/appservice/__dev__/WAService.js:1:577776)
    at b (http://127.0.0.1:33360/appservice/__dev__/WAService.js:1:555243)
    at o.doUpdates (http://127.0.0.1:33360/appservice/__dev__/WAService.js:1:556455)
    at t.applyProperties (http://127.0.0.1:33360/appservice/__dev__/WAService.js:1:641575)
```

taro info
```
Taro CLI 1.2.7 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
    npmPackages:
      @tarojs/components: 1.2.7 => 1.2.7
      @tarojs/plugin-babel: 1.2.7 => 1.2.7
      @tarojs/plugin-csso: 1.2.7 => 1.2.7
      @tarojs/plugin-sass: 1.2.7 => 1.2.7
      @tarojs/plugin-uglifyjs: 1.2.7 => 1.2.7
      @tarojs/router: 1.2.7 => 1.2.7
      @tarojs/taro: 1.2.7 => 1.2.7
      @tarojs/taro-alipay: 1.2.7 => 1.2.7
      @tarojs/taro-h5: 1.2.7 => 1.2.7
      @tarojs/taro-swan: 1.2.7 => 1.2.7
      @tarojs/taro-weapp: 1.2.7 => 1.2.7
      @tarojs/webpack-runner: 1.2.7 => 1.2.7
      eslint-config-taro: 1.2.7 => 1.2.7
      eslint-plugin-taro: 1.2.7 => 1.2.7
    npmGlobalPackages:
      typescript: 2.8.3
```

taro ui版本：
2.0.0-beta1

**Comment by koppthe** [comment]
有可以复现的 demo 吗？试了好几个环境都是正常的。

**Comment by seveny** [comment]
这个问题解决了吗，现在也遇到这个报错

**Comment by zhangfu-git** [comment]
老项目升级了Taro， 出现类似的问题

**Comment by RianMan** [comment]
我也是这个问题 怎么解决的

**Comment by nevernet** [comment]
`designWidth` 确实是一个很奇怪的， 我现在升级到最新版的taro-ui，有时候也会碰到。
没有仔细深入研究， 猜测taro-ui底层涉及到这个地方需要重新架构。

**Comment by koppthe** [comment]
@nevernet 有升级到 taro v1.3.11 吗？

**Comment by ThatRoy** [comment]
taro-ui v2.2.1 , taro v1.3.11 ，在使用 AtRate  组件时，也出现了这个问题

**Comment by ThatRoy** [comment]
@koppthe taro-ui v2.2.1 , taro v1.3.11 ，在使用 AtRate 组件时，也出现了这个问题

**Comment by ThatRoy** [comment]
@koppthe 可以看下你正常情况下的 taro info 信息吗
