### ISSUE TITLE
AtTabBar 在win下切换时报错

### ISSUE THREAD

**Issue by zhangyanfei19881201** [NervJS/taro-ui#357]
**问题描述**
问题如
https://github.com/NervJS/taro-ui/issues/209
版本1.2.7、1.2.3均有复现
node: 8.11.3
[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
仅在win7下复现，mac上无法复现
**复现步骤**
[复现问题的步骤]
1. 新建项目，安装npm install
2.  安装CLI npm install @tarojs/cli
3. 添加tab代码到pages/index/index.js
4. npm run dev:weapp
5.在微信开发者工具中切换tab，此时无法切换，并且控制台输出错误信息

```js
  render() {
    return (
      <View className='index'>
        <AtTabBar
          tabList={[
            { title: '待办事项', text: 8 },
            { title: '拍照' },
            { title: '通讯录', dot: true }
          ]}
        />
      </View>
    )
  }
```

**期望行为**
期望正常切换，控制台无错误

**报错信息**
Thu Jan 17 2019 23:50:21 GMT+0800 (中国标准时间) 渲染层错误
VM9171:2 webviewScriptError
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
    at g (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:20:4992)
    at o.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:20:6112)
    at r.safeCallback (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:28628)
    at r.call (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:28392)
    at n (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:30858)
    at http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:31412
    at s (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:30426)
    at Function.r.dispatchEvent (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:31313)
    at t (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:7:24832)
    at v (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:7:25317)

VM9173:1 Thu Jan 17 2019 23:50:21 GMT+0800 (中国标准时间) 渲染层错误
VM9173:2 [Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)

Thu Jan 17 2019 23:50:21 GMT+0800 (中国标准时间) 渲染层错误
VM9174:2 TypeError: Cannot read property 'offsetLeft' of undefined
    at g (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:20:4992)
    at o.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:20:6112)
    at r.safeCallback (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:28628)
    at r.call (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:28392)
    at n (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:30858)
    at http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:31412
    at s (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:30426)
    at Function.r.dispatchEvent (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:5:31313)
    at t (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:7:24832)
    at v (http://127.0.0.1:56491/__pageframe__/__dev__/WAWebview.js:7:25317)

**系统信息**
👽 Taro v1.2.7

  Taro CLI 1.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.3 - D:\02software\node\nodejs\node.EXE
      Yarn: 1.5.1 - D:\02software\node\npm\yarn.CMD
      npm: 6.0.0 - D:\02software\node\npm\npm.CMD

 - Taro 版本 [e.g. v1.2.7]
 - Taro UI 版本 [e.g. v1.2.7]
 - 报错平台 [weapp]

**Comment by koppthe** [comment]
微信基础库的版本是多少？找了一台 windows 7 也没法重现。
