### ISSUE TITLE
taro-ui自定义主题失败

### ISSUE THREAD

**Issue by StephenOo** [NervJS/taro-ui#368]
**问题描述**
按照taro-ui官方文档的步骤设置自定义主题颜色，失败

**复现步骤**
按照taro-ui自定义主题，scss主题变量覆盖的方法在项目中自定义主题，然后失败
```js
//custom-variables.scss
/* 改变主题变量，具体变量名可查看 taro-ui/dist/style/variables/default.scss 文件 */
$color-brand: #3BBE64
/* 引入 Taro UI 默认样式 */
@import "~taro-ui/dist/style/index.scss"

//app.tsx
import './custom-variables.scss'

//保存项目，命令行报错
{ Error: Invalid CSS after "...默认样式 */": expected expression (e.g. 1px, bold), was '@import "~taro-ui/d'
    at Object.module.exports.renderSync (D:\project\wx-demo\taro-yunqiu\node_modules\_node-sass@4.11.0@node-sass\lib\index.js:439:16)
    at Promise (D:\project\wx-demo\taro-yunqiu\node_modules\_@tarojs_plugin-sass@1.2.7@@tarojs\plugin-sass\index.js:11:21)
    at new Promise (<anonymous>)
    at compileSass (D:\project\wx-demo\taro-yunqiu\node_modules\_@tarojs_plugin-sass@1.2.7@@tarojs\plugin-sass\index.js:4:10)
    at Object.callPlugin (C:\Program Files\nodejs\node_global\node_modules\@tarojs\cli\src\util\npm.js:122:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
  status: 1,

```

**期望行为**
实现ui主题颜色的自定义

**系统信息**

例子：
 - Taro 版本 [e.g. v.1.2.8]
 - Taro UI 版本 [e.g. v.1.5.4]
 - 报错平台 [h5, weapp]

**Comment by shaodushu** [comment]
$color-brand: #3BBE64;  少了个分号

**Comment by shaodushu** [comment]
缺少分号

**Comment by koppthe** [comment]
taro-ui 的版本要 v2.0.0+，v1.5.4 不支持变量覆盖的方式

**Comment by smz8023** [comment]
> taro-ui 的版本要 v2.0.0+，v1.5.4 不支持变量覆盖的方式

你好，我想问一下，如何通过一个按钮来改变主题颜色？
例如：$color-brand: red;

@import "~taro-ui/dist/style/index.scss";
我现在jsx文件中通过button事件改变这个变量，使主题颜色改变？
