### ISSUE TITLE
开始cssMoudules，依然报错Cannot read property 'exports' of undefined

### ISSUE THREAD

**Issue by jeremyChenMing** [NervJS/taro-ui#396]
**问题描述**
在看过官网后，我开启的cssMoudles功能
如下，config/index.js中
      cssModules: {
          enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
在pages/index/index.js中引用如下 import l from './index.less';
结果在控制台中报错如下
TypeError: Cannot read property 'exports' of undefined
at ImportDeclaration (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:447:36)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)

taro info 信息在这里
👽 Taro v1.2.12

  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.12 => 1.2.12 
      @tarojs/plugin-babel: 1.2.12 => 1.2.12 
      @tarojs/plugin-csso: 1.2.12 => 1.2.12 
      @tarojs/plugin-less: 1.2.12 => 1.2.12 
      @tarojs/plugin-uglifyjs: 1.2.12 => 1.2.12 
      @tarojs/router: 1.2.12 => 1.2.12 
      @tarojs/taro: 1.2.12 => 1.2.12 
      @tarojs/taro-alipay: 1.2.12 => 1.2.12 
      @tarojs/taro-h5: 1.2.12 => 1.2.12 
      @tarojs/taro-swan: 1.2.12 => 1.2.12 
      @tarojs/taro-tt: 1.2.12 => 1.2.12 
      @tarojs/taro-weapp: 1.2.12 => 1.2.12 
      @tarojs/webpack-runner: 1.2.12 => 1.2.12 
      eslint-config-taro: 1.2.12 => 1.2.12 
      eslint-plugin-taro: 1.2.12 => 1.2.12 
      nervjs: ^1.3.9 => 1.3.12

我应该怎么补救？

**Comment by luckyadam** [comment]
请仔细阅读一下文档
https://nervjs.github.io/taro/docs/css-modules.html

**Comment by jeremyChenMing** [comment]
我确实读了几遍了，感觉跟我相关的就那一点点内容！还请帮忙查找下@luckyadam

**Comment by jeremyChenMing** [comment]
在说明一点，用的是less，试了好几遍了！在h5中倒是不报错，可是import l from './index.less'中l没有任何值

**Comment by jeremyChenMing** [comment]
懂了懂了，原来是文件名字加module，ok！
