### ISSUE TITLE
taro-ui导致jest测试组件不通过

### ISSUE THREAD

**Issue by yzl548776178** [NervJS/taro-ui#417]
**问题描述**
Taro项目使用jest测试时，taro-ui报错。

**复现步骤**

index.js
```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Image } from '@tarojs/components'
import { AtIcon } from 'taro-ui'
import './index.scss'
```
err
```bash
 FAIL  src/components/TaskItem/index.test.js
  ● Test suite failed to run

    /Users/yzliang/cm-store-steward/node_modules/_taro-ui@2.0.1@taro-ui/dist/weapp/index.js:2
    import Taro from '@tarojs/taro'
           ^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/_jest-runtime@23.6.0@jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/_taro-ui@2.0.1@taro-ui/dist/index.js:5:22)
```

**期望行为**
可以正常通过测试

**报错信息**
![image](https://user-images.githubusercontent.com/23308548/53236061-58a6cc80-36ce-11e9-80e3-ad8d7bde04ea.png)

**系统信息**
 - Taro 版本 [v1.2.8]
 - Taro UI 版本 [v2.0.1]
 - 报错平台 [h5]

**Comment by SzHeJason** [comment]
? 这是不支持 es6 语法 配置一下 babel 另外 参考 taro-ui 的配置方式

**Comment by jimczj** [comment]
这个跟 Taro-UI 无关，可以参考 Taro-UI 怎么配置 jest
