### ISSUE TITLE
安装包的时候到node-sass 这一步失败了

### ISSUE THREAD

**Issue by luckly-boy** [NervJS/taro-ui#428]
**问题描述**
安装包的时候到node-sass 这一步失败了
**复现步骤**
`{
  "name": "taro",
  "version": "1.0.0",
  "private": true,
  "description": "taro",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "^1.2.12",
    "@tarojs/mobx": "^1.2.13",
    "@tarojs/mobx-h5": "^1.2.13",
    "@tarojs/mobx-rn": "^1.2.13",
    "@tarojs/router": "^1.2.12",
    "@tarojs/taro": "^1.2.12",
    "@tarojs/taro-alipay": "1.2.7",
    "@tarojs/taro-h5": "^1.2.12",
    "@tarojs/taro-swan": "1.2.7",
    "@tarojs/taro-tt": "1.2.7",
    "@tarojs/taro-weapp": "^1.2.12",
    "miment": "0.0.8",
    "mobx": "4.8.0",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "2.0.0"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "^1.2.12",
    "@tarojs/plugin-csso": "^1.2.12",
    "@tarojs/plugin-less": "^1.2.12",
    "@tarojs/plugin-sass": "^1.2.12",
    "@tarojs/plugin-uglifyjs": "^1.2.12",
    "@tarojs/webpack-runner": "^1.2.12",
    "@types/react": "^16.8.2",
    "@types/webpack-env": "^1.13.7",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^1.2.12",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-taro": "^1.2.12"
  }
}
`

**期望行为**
正常安装
**报错信息**
`yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.6: The platform "win32" is incompatible with this module.
info "fsevents@1.2.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@tarojs/mobx-rn > @tarojs/taro-rn > react-native-image-zoom-viewer@2.2.25" has unmet peer dependency "react@*".
warning "@tarojs/mobx-rn > @tarojs/taro-rn > react-native-image-zoom-viewer@2.2.25" has unmet peer dependency "react-native@*".
warning "@tarojs/mobx-rn > @tarojs/taro-rn > react-native-root-toast@3.0.2" has unmet peer dependency "react-native@>=0.47.0".
warning "@tarojs/mobx-rn > @tarojs/taro-rn > react-native-image-zoom-viewer > react-native-image-pan-zoom@2.1.11" has unmet peer dependency "react@*".
warning "@tarojs/mobx-rn > @tarojs/taro-rn > react-native-image-zoom-viewer > react-native-image-pan-zoom@2.1.11" has unmet peer dependency "react-native@*".
[4/4] Building fresh packages...
[-/3] ⡀ waiting...
[2/3] ⡀ node-sass
error D:\git\test\app\wx_recipeTalent\node_modules\@tarojs\plugin-sass\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\git\test\app\wx_recipeTalent\node_modules\@tarojs\plugin-sass\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe D:\git\test\app\wx_recipeTalent\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\test\app\wx_recipeTalent\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\test\app\wx_recipeTalent\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\test\app\wx_recipeTalent\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\test\app\wx_recipeTalent\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\test\app\wx_recipeTalent\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\which\\which.js:13:12)\n    at F (D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\which\\which.js:68:19)\n    at E (D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\which\\which.js:80:29)\n    at D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\which\\which.js:89:16\n    at D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\isexe\\index.js:42:5\n    at D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\yes\AppData\Local\Programs\Python\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\yes\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\git\\test\\app\\wx_recipeTalent\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\git\test\app\wx_recipeTalent\node_modules\@tarojs\plugin-sass\node_modules\node-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok`
**系统信息**
taro-ui 2.0.0

**Comment by luckly-boy** [comment]
已解决，yarn安装有问题，用npm就好了
