### ISSUE TITLE
（小程序）引入 AtActivityIndicator 组件报错

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#5]
```
TypeError: Cannot read property 'replace' of null
    at buildSingleComponent (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1330:37)
    at buildSingleComponent (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1388:20)
    at buildSingleComponent (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1388:20)
    at Promise.all.componentPathList.map.componentObj (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1295:60)
    at Array.map (<anonymous>)
    at buildDepComponents (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1295:40)
    at buildSinglePage (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1136:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.relative (path.js:1173:5)
    at pageDepComponents.forEach.depComponent (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1150:64)
    at Array.forEach (<anonymous>)
    at componentMap.forEach.component (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1144:31)
    at Array.forEach (<anonymous>)
    at realComponentsPathList.forEach.component (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1143:24)
    at Array.forEach (<anonymous>)
    at buildSinglePage (/Users/kenberkeley/Desktop/my-project/node_modules/_@tarojs_cli@1.0.0-beta.17@@tarojs/cli/src/weapp.js:1140:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kenberkeley** [comment]
### 复现步骤

```
> cnpm i -g @tarojs/cli@1.0.0-beta.17
> taro init taro1beta17
> cd taro1beta17
> cnpm i -S taro-ui
> npm run dev:weapp
```

修改 `src/pages/index/index.js` 为：

```jsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtActivityIndicator } from 'taro-ui'

export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  }

  render () {
    return (
      <View>
        <AtActivityIndicator />
      </View>
    )
  }
}
```

**Comment by kenberkeley** [comment]
@SzHeJason  谢谢~

**Comment by koppthe** [comment]
在 beta.4 中已修复，预计今天或明天会发布 v1.0.0 正式版

**Comment by kenberkeley** [comment]
@koppthe 关闭 issue 建议注明 commit id，例如 https://github.com/NervJS/taro-ui/commit/5ff27af0ecbf08639bd76cf1a54a1d35afff860c

**Comment by koppthe** [comment]
感谢建议，把这个给忘了🤣
