### ISSUE TITLE
AtImagePicker组件编译失败

### ISSUE THREAD

**Issue by TonyLiuYan** [NervJS/taro-ui#543]
**问题描述**

使用 AtImagePicker 组件，在编译时控制台提示编译失败
**复现步骤**
按照官方文档，在项目中使用AtImagePicker控件，一旦在render中使用了AtImagePicker组件，控制台中就会提示编译失败，使用方式和代码完全按照官方文档方式

```js
import Taro from '@tarojs/taro'
import { AtImagePicker } from 'taro-ui'
export default class Index extends Taro.Component {
  constructor () {
    super(...arguments)
    this.state = {
      files: [{
        url: 'https://jimczj.gitee.io/lazyrepay/aragaki1.jpeg',
      },
      {
        url: 'https://jimczj.gitee.io/lazyrepay/aragaki2.jpeg',
      },
      {
        url: 'https://jimczj.gitee.io/lazyrepay/aragaki3.png',
      }]
    }
  }
  onChange (files) {
    this.setState({
      files
    })
  }
  onFail (mes) {
    console.log(mes)
  }
  onImageClick (index, file) {
    console.log(index, file)
  }
  render () {
    return (
      <AtImagePicker
        files={this.state.files}
        onChange={this.onChange.bind(this)}
      />
    )
  }
}


```

**期望行为**
可以正常使用，编译通过

**报错信息**
生成  依赖文件  dist/ui/wux/button/index.js
修改  页面文件  src/pages/publish/xinqing/index
编译  页面文件  src/pages/publish/xinqing/index
编译  组件文件  node_modules/taro-ui/dist/index.js
编译  组件文件  node_modules/taro-ui/dist/weapp/index.js
编译  组件文件  node_modules/taro-ui/dist/weapp/components/image-picker/index.js
错误  组件编译  组件node_modules/taro-ui/dist/weapp/components/image-picker/index.js编译失败！
{ TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"
    at validate (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\definitions\index.js:109:13)
    at Object.validate (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\definitions\core.js:412:50)
    at Object.validate (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\replacement.js:176:7)
    at NodePath.replaceWith (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\replacement.js:160:8)
    at replaceAndEvaluateNode (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-define@1.3.1@babel-plugin-transform-define\lib\index.js:117:12)
    at processNode (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-define@1.3.1@babel-plugin-transform-define\lib\index.js:143:5)
    at PluginPass.Identifier (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-define@1.3.1@babel-plugin-transform-define\lib\index.js:23:9)
    at newFn (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:76:18) _babel: true }
生成  页面配置  dist/pages/publish/xinqing/index.json
生成  页面逻辑  dist/pages/publish/xinqing/index.js
生成  页面模板  dist/pages/publish/xinqing/index.wxml
生成  页面样式  dist/pages/publish/xinqing/index.wxss
错误  页面编译  页面D:\wechat\FutureLetter\src\pages\publish\xinqing\index编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1677:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1676:44)
    at buildSinglePage (C:\Users\tonyy\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1433:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**系统信息**
windows10

"dependencies": {
    "@tarojs/components": "1.2.23",
    "@tarojs/mobx": "1.2.23",
    "@tarojs/mobx-h5": "1.2.23",
    "@tarojs/mobx-rn": "1.2.23",
    "@tarojs/rn-runner": "1.2.23",
    "@tarojs/router": "1.2.23",
    "@tarojs/taro": "1.2.23",
    "@tarojs/taro-alipay": "1.2.23",
    "@tarojs/taro-h5": "1.2.23",
    "@tarojs/taro-swan": "1.2.23",
    "@tarojs/taro-tt": "1.2.23",
    "@tarojs/taro-weapp": "1.2.23",
    "mobx": "4.8.0",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.1.0"
  },

**补充信息**

**Comment by jimczj** [comment]
麻烦升级下 Taro 版本吧
