### ISSUE TITLE
taro-ui 不可用在less编译的脚手架中

### ISSUE THREAD

**Issue by 891806797** [NervJS/taro-ui#545]
请问我们这个taro-ui啥时候支持less啊？

**Comment by koppthe** [comment]
你在 JS 里面引入 `taro-ui` 的样式就好了

**Comment by sunkaigoon** [comment]
在less编译的脚手架中使用taro-ui会报一个错误

> { [Error: './libs/hairline' wasn't found. Tried - /Users/***/Project/taro-myApp/node_modules/taro-ui/dist/style/mixins/libs/hairline.less,libs/hairline.less]
  message:
   '\'./libs/hairline\' wasn\'t found. Tried - /Users/***/Project/taro-myApp/node_modules/taro-ui/dist/style/mixins/libs/hairline.less,libs/hairline.less',
  stack: undefined,
  type: 'File',
  filename:
   '/Users/sunkai/Project/taro-myApp/node_modules/taro-ui/dist/style/mixins/index.scss',
  index: 348,
  line: 18,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract:
   [ '@import \'./libs/alignhack\';',
     '@import \'./libs/hairline\';',
     '' ] }
TypeError: Cannot read property 'css' of undefined
    at /Users/sunkai/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/compileStyle.js:157:28
    at Generator.next (<anonymous>)
    at /Users/sunkai/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/compileStyle.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sunkai/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/compileStyle.js:3:12)
    at processStyleWithPostCSS (/Users/sunkai/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/compileStyle.js:91:12)
    at Promise.all.resList.map.res (/Users/sunkai/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/compileStyle.js:237:46)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/sunkai/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/compileStyle.js:237:35)
    at Generator.next (<anonymous>)

/taro-ui/dist/style/mixins/libs/hairline.scss是存在的
/taro-ui/dist/style/mixins/libs/hairline.less不存在，但是编译过程好像就是找的.less的文件，所以找不到报错

@koppthe

**Comment by RianMan** [comment]
@koppthe  那样的话是不是就不是按需加载了呢

**Comment by koppthe** [comment]
也可以啊，你可以按需要在 JS 中引入对应的 scss 文件
