### ISSUE TITLE
缺少npm包@tarojs/plugin-sass，开始安装...

### ISSUE THREAD

**Issue by Biime** [NervJS/taro-ui#70]
引入组件后 会提示 **缺少npm包@tarojs/plugin-sass，开始安装...**

然后就是一大堆错误，请问这应该怎么解决啊？

```
Cannot download "https://r.cnpmjs.org/node-sass//v4.9.3/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Temp\\wxxcx\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.8.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://r.cnpmjs.org/node
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Temp\wxxcx\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Temp\wxxcx\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Temp\wxxcx\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Temp\wxxcx\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Temp\wxxcx\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Temp\wxxcx\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Temp\wxxcx\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Temp\wxxcx\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Temp\wxxcx\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Temp\wxxcx\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Temp\wxxcx\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Temp\wxxcx\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (D:\\Temp\\wxxcx\\node_modules\\which\\which.js:13:12)\n    at F (D:\\Temp\\wxxcx\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Temp\\wxxcx\\node_modules\\which\\which.js:80:29)\n    at D:\\Temp\\wxxcx\\node_modules\\which\\which.js:89:16\n    at D:\\Temp\\wxxcx\\node_modules\\isexe\\index.js:42:5\n    at D:\\Temp\\wxxcx\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\lenovo\AppData\Local\Programs\Python\Python36\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\lenovo\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:288:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Temp\\wxxcx\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Temp\wxxcx\node_modules\node-sass
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
错误  组件编译  组件node_modules/taro-ui/dist/weapp/components/loading/index.js编译失败！
{ Error: Cannot find module '@tarojs/plugin-sass' from 'D:\Temp\wxxcx'
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\resolve\lib\async.js:51:31
    at processDirs (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\resolve\lib\async.js:185:39)
    at ondir (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\resolve\lib\async.js:200:13)
    at load (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\resolve\lib\async.js:83:43)
    at onex (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\resolve\lib\async.js:108:17)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\resolve\lib\async.js:12:69
    at FSReqWrap.oncomplete (fs.js:152:21) code: 'MODULE_NOT_FOUND' }
生成  组件JSON  dist/dist/taro-ui/dist/weapp/components/button/index.json
生成  组件JS    dist/dist/taro-ui/dist/weapp/components/button/index.js
生成  组件WXML  dist/dist/taro-ui/dist/weapp/components/button/index.wxml
生成  组件WXSS  dist/dist/taro-ui/dist/weapp/components/button/index.wxss
错误  组件编译  组件node_modules/taro-ui/dist/weapp/components/button/index.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1308:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1307:44)
    at buildSingleComponent (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1484:28)
生成  页面JSON  dist/pages/index/index.json
生成  页面JS    dist/pages/index/index.js
生成  页面WXML  dist/pages/index/index.wxml
生成  页面WXSS  dist/pages/index/index.wxss
错误  页面编译  页面D:\Temp\wxxcx\src\pages\index\index编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1308:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1307:44)
    at buildSinglePage (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1176:28)
```

**Comment by jimczj** [comment]
翻墙，cnpm，yarn，总有一个适合你

**Comment by Tom9402** [comment]
同问

**Comment by Tom9402** [comment]
我装了个 yarn 就解决了……
