### ISSUE TITLE
继承 taro UI 组件编译出错

### ISSUE THREAD

**Issue by hqman** [NervJS/taro-ui#715]
#  继承 taro UI 组件编译出错

```javascript
import Taro from '@tarojs/taro'
import { AtListItem } from "taro-ui";
import { View, Image, Switch, Text } from '@tarojs/components'
import PropTypes from 'prop-types'
import classNames from 'classnames'
import _isFunction from 'lodash/isFunction'



export default class MyListItem extends AtListItem {
..........
}
```

```
(node:14944) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/xxx/project/smq3/mp_client/node_modules/taro-ui/dist/weapp/style/index.scss'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:227:30
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:226:12)
    at analyzeImportUrl (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:122:17)
    at ImportDeclaration (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:176:25)
(node:14944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

- Taro 版本 [v1.3.10]
- Taro UI 版本 [v2.2.1]

**Comment by xcj189323200** [comment]
这个问题有答案没

**Comment by hqman** [comment]
@luckyadam  大佬 支持一下！

**Comment by zeegb** [comment]
@luckyadam 同样的问题。继承自定义的组件也会报找不到taro-ui的scss...

**Comment by zeegb** [comment]
@hqman 有解决吗？
