### ISSUE TITLE
taro-ui安装后报错：找不到./components/calendar

### ISSUE THREAD

**Issue by ggx900706** [NervJS/taro-ui#864]
### Taro UI 版本信息

2.2.4

### 问题描述

taro-ui装上后报错：本来应用没有问题，可以跑rn和h5端，但是安装taro-ui后报错，内容是找不到./components/calendar。

### 复现步骤

1、正常新建taro应用，开发功能，支持RN和h5端；
2、sudo yarn add taro-ui；
3、yarn dev:rn或yarn dev:h5；
4、RN等控制台报错即可，h5等网页报错即可。

### 复现代码

无特殊代码，仅安装taro-ui依赖

### 报错信息

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./components/calendar` from `/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/taro-ui/dist/weapp/index.js`: The module `./components/calendar` could not be found from `/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/taro-ui/dist/weapp/index.js`. Indeed, none of these files exist:

  * `/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/taro-ui/dist/weapp/components/calendar(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/taro-ui/dist/weapp/components/calendar/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at /Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/gaoguanxiong/Desktop/test/rnTest/taroH5/mapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [android, dev] rn_temp/index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.4% (1108/1234), failed.

### 系统信息

macbook：10.15.1
node：12.13.0
taro：1.3.22
taro-ui：2.2.4

### 补充信息

请尽快联系我，谢谢。联系方式：微信13691505478或qq875305085

**Comment by byk04712** [comment]
遇到同样的问题，在 npm run dev:rn 时遇到找不到 calendar

**Comment by Garfield550** [comment]
Taro UI 不支持 RN
