### ISSUE TITLE
taro-ui/dist/style/components/range.scss  line6

### ISSUE THREAD

**Issue by chenyongze** [NervJS/taro-ui#886]
Error: Incompatible units: 'PX' and 'px'.
    at Object.module.exports.renderSync (/Users/yongze/Documents/workspace/xgk-pro/xgk-coupon/taro-xgk-coupon/node_modules/_node-sass@4.13.0@node-sass/lib/index.js:439:16)
    at /Users/yongze/Documents/workspace/xgk-pro/xgk-coupon/taro-xgk-coupon/node_modules/_@tarojs_plugin-sass@1.3.26@@tarojs/plugin-sass/index.js:58:21
    at new Promise (<anonymous>)
    at compileSass (/Users/yongze/Documents/workspace/xgk-pro/xgk-coupon/taro-xgk-coupon/node_modules/_@tarojs_plugin-sass@1.3.26@@tarojs/plugin-sass/index.js:5:10)
    at Object.<anonymous> (/Users/yongze/Documents/workspace/xgk-pro/xgk-coupon/taro-xgk-coupon/node_modules/_@tarojs_cli@1.3.26@@tarojs/cli/dist/util/npm.js:133:12)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yongze/Documents/workspace/xgk-pro/xgk-coupon/taro-xgk-coupon/node_modules/_@tarojs_cli@1.3.26@@tarojs/cli/dist/util/npm.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: 1,
  file: '/Users/yongze/Documents/workspace/xgk-pro/xgk-coupon/taro-xgk-coupon/node_modules/taro-ui/dist/style/components/range.scss',
  line: 6,
  column: 14,
  message: "Incompatible units: 'PX' and 'px'.",
  formatted: "Error: Incompatible units: 'PX' and 'px'.\n" +
    '        on line 6 of node_modules/taro-ui/dist/style/components/range.scss\n' +
    '        from line 39 of node_modules/taro-ui/dist/style/components/index.scss\n' +
    '        from line 12 of node_modules/taro-ui/dist/style/index.scss\n' +
    '        from line 4 of src/assets/taro-ui-custom.scss\n' +
    '>>   padding: 0 $at-range-slider-size / 2 + 4PX;\n' +
    '\n' +
    '   -------------^\n'

**Comment by Garfield550** [comment]
无法复现，在 Taro 中 PX 是合法单位。

> 如果你希望部分 px 单位不被转换成 rpx 或者 rem ，最简单的做法就是在 px 单位中增加一个大写字母，例如 Px 或者 PX 这样，则会被转换插件忽略。

https://nervjs.github.io/taro/docs/size.html#docsNav
