### ISSUE TITLE
安装taro ui后项目无法找到组件

### ISSUE THREAD

**Issue by lanmch** [NervJS/taro-ui#978]
**问题描述**

项目安装taro ui后 提示

**复现步骤**

100%复现

```js
Cannot read property 'defaultProps' of undefined
TypeError: Cannot read property 'defaultProps' of undefined

Component is not found in path "npm/taro-ui/dist/weapp/components/tabs/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/tabs/index" (using by "pages/index/index")
```

**期望行为**

**报错信息**

```js
// 两个报错

VM17:1 thirdScriptError
Cannot read property 'defaultProps' of undefined
TypeError: Cannot read property 'defaultProps' of undefined
    at Object.createComponent (http://127.0.0.1:27987/appservice/vendors.js:3295:51)
    at Object../node_modules/_taro-ui@2.3.0@taro-ui/dist/weapp/components/tabs/index.tsx (http://127.0.0.1:27987/appservice/npm/taro-ui/dist/weapp/components/tabs/index.js:298:145)
    at __webpack_require__ (http://127.0.0.1:27987/appservice/runtime.js:80:30)
    at checkDeferredModules (http://127.0.0.1:27987/appservice/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:27987/appservice/runtime.js:33:19)
    at http://127.0.0.1:27987/appservice/npm/taro-ui/dist/weapp/components/tabs/index.js:1:620
    at require (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1671737)
    at <anonymous>:20:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:27987/appservice/appservice?t=1583853394757:1254:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:27987/appservice/appservice?t=1583853394757:1266:20)


VM17:1 jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/tabs/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/tabs/index" (using by "pages/index/index")
    at G (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1526161)
    at G (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1526365)
    at http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1547723
    at Module.Ue (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1548302)
    at Function.value (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1631292)
    at Tt (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1647404)
    at http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1651666
    at xt (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1652159)
    at Function.<anonymous> (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1655744)
    at i.<anonymous> (http://127.0.0.1:27987/appservice/__dev__/WAService.js:2:1624244)
```
**系统信息**

Taro CLI 2.0.0-beta.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - F:\node\node.EXE
      Yarn: 1.13.0 - C:\Users\Mch\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - F:\node\npm.CMD
**补充信息**

前几天构建某个项目 cnpm taro-ui 是在node_mo文件夹下直接有一个taro-ui文件夹
今天构建 无论什么项目 只要使用cnpm安装 node_mo文件夹下是一个_taro-ui@版本的文件夹
文件夹下对应文件即如问题描述代码中所报defaultProps错误（引入路径错误）
如果使用yarn add安装taro ui 可成功安装taro-ui的包 但是此时npm run dev:weapp是 无法成功运行项目

**Comment by Garfield550** [comment]
Taro CLI 2.0.0-beta.13 问题很多，Taro 的依赖更新到 2.0.5 再试一下

**Comment by Garfield550** [comment]
https://github.com/Garfield550/taro-ui-troubleshooting/tree/issue-960 你可以 clone 这个分支然后 `yarn install` 下，应该会编译成功。

**Comment by zhqinux** [comment]
我这里也出现了这样的情况
taro init 项目后
cnpm install taro-ui

app.js中
import 'taro-ui/dist/style/index.scss'

我只是在这个新项目的index.jsx中导入了AtButton后项目就跑不起来了

但是命令行那里提示的是编译成功，而微信小程序开发工具那里提示的就是类似于

VM17:1 jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index");onAppRoute

我的taro/cli的版本是2.0.7

我只是想试试这个框架，所以小程序那里没有提供AppId

**Comment by aa-ziyi** [comment]
用的@tarojs/cli 2.2.2的版本确实有问题
重新装 npm install -g @tarojs/cli@1.3.12   的版本
重新init一个项目正常了，其他版本还没试

**Comment by smartwange** [comment]
> https://github.com/Garfield550/taro-ui-troubleshooting/tree/issue-960 你可以 clone 这个分支然后 `yarn install` 下，应该会编译成功。

Cannot read property 'hooks' of undefined
(node:14116) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
